name: Fortran build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [serial]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ build environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install serial/parallel compiler
      run: |
        if [ "${{ matrix.compiler }}" = "serial" ]; then
          sudo apt-get install g++
        else
          sudo apt-get install g++-9
        fi
    - name: Compile MossGrowth
      run: |
       cd Exec
       make
       ls
    - name: Run C++ program with serial/parallel executable
      run: |
        cd Exec
        if [ "${{ matrix.compiler }}" = "serial" ]; then
          ./moss_growth.ex
        else
          ./moss_growth.ex
        fi
